project_id = "yecfogakgyszdkipzelm"

[functions.avaliar-redacao]
verify_jwt = false

[functions.chat-aprovia]
verify_jwt = false

[functions.professora-enem]
verify_jwt = false

[functions.resolver-questao]
verify_jwt = false

[functions.text-to-speech-enem]
verify_jwt = false
